### ISSUE TITLE
Trying to create homebrew formula

### ISSUE THREAD

**Issue by diasjorge** [alk/gpicker#7]
I'm trying to get gpicker installed on osx.

I already installed gtk+ using homebrew which just made it very easy, unfortunately jhbuild seems to conflict with homebrew, although I'm not entirely sure about this.

Anyway, I've downloaded this repo, and I notice there is no ./configure but a configure.ac.in, I guess I'd have to use autoconf on this file first, am I right?

anyway I did this:

autoconf configure.ac.in 

but I'm getting this error:

configure.ac.in:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac.in:16: error: possibly undefined macro: AM_CONDITIONAL

Do you have any clues what could this mean, I guess it's some of the macros are not available for autconf but I'm very new with all this.

Any help would be truly appreciated.

Greetings

**Comment by jojojames** [comment]
brew install gtk+
./configure
make && make install

works for me on OSX El Captain.
